Fixed AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key' The error is due to latest version of protobuf which is not supported by python3-grpcio-tools, the way to overcome it is to use grpcio-tools version 1.29.0